project_id = "otixzjugohqzfvtrogqj"

[functions.fetch-resort-data]
verify_jwt = false

[functions.fetch-lodging]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false

[functions.fetch-flights]
verify_jwt = false
